-- Note: you must use SQLCMD mode for this script
:r '01dbo.CleanUpTDCObjects.sql'
:r '02dbo.usp_tdc_create_schema.sql'
:r '03dbo.ufn_tdc_objects_exists.sql'
:r '04dbo.ufn_is_tdc_enabled.sql'
:r '05dbo.usp_tdc_enable_db.sql'
:r '06dbo execute usp_tdc_enable_db.sql'
:r '07dbo.usp_tdc_disable_db.sql'
:r '08tdc.usp_GetColumnInfo.sql'
:r '09tdc.usp_GetJoinInfo.sql'
:r '10tdc.usp_tdc_enable_table_internal.sql'
:r '11tdc.usp_tdc_disable_table.sql'
:r '12tdc.usp_tdc_enable_table.sql'
:r '13tdc.ufn_ColumnType.sql'
:r '14tdc.usp_CanTableBeTDC_Enabled.sql'