USE [master]
ALTER DATABASE [TemporalTest] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [TemporalTest] FROM  DISK = N'C:\DBBackups\TemporalTest.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [TemporalTest] SET MULTI_USER

GO


